export enum CompetitionType {
  HIGHEST_RETURN = 'HIGHEST_RETURN',
  MOST_VOLUME = 'MOST_VOLUME',
  BEST_SHARPE = 'BEST_SHARPE',
  HIGHEST_WINS = 'HIGHEST_WINS',
  LOWEST_DRAWDOWN = 'LOWEST_DRAWDOWN'
}

export enum DurationType {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  CUSTOM = 'CUSTOM'
}

export enum CompetitionStatus {
  UPCOMING = 'UPCOMING',
  ACTIVE = 'ACTIVE',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED'
}

export enum ParticipantStatus {
  REGISTERED = 'REGISTERED',
  ACTIVE = 'ACTIVE',
  FINISHED = 'FINISHED',
  DISQUALIFIED = 'DISQUALIFIED',
  WITHDRAWN = 'WITHDRAWN'
}

export enum TradeSide {
  BUY = 'BUY',
  SELL = 'SELL'
}

export enum AchievementType {
  FIRST_PLACE = 'FIRST_PLACE',
  TOP_THREE = 'TOP_THREE',
  TOP_TEN = 'TOP_TEN',
  HIGHEST_RETURN = 'HIGHEST_RETURN',
  MOST_VOLUME = 'MOST_VOLUME',
  BEST_RISK_ADJUSTED = 'BEST_RISK_ADJUSTED',
  WIN_STREAK = 'WIN_STREAK',
  CONSISTENT_PERFORMANCE = 'CONSISTENT_PERFORMANCE'
}

export enum FlagType {
  WASH_TRADING = 'WASH_TRADING',
  SELF_DEALING = 'SELF_DEALING',
  MANIPULATION = 'MANIPULATION',
  BOTS = 'BOTS',
  MULTIPLE_ACCOUNTS = 'MULTIPLE_ACCOUNTS',
  UNUSUAL_PATTERN = 'UNUSUAL_PATTERN'
}

export enum FlagSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum FlagStatus {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  CONFIRMED = 'CONFIRMED',
  DISMISSED = 'DISMISSED',
  ACTION_TAKEN = 'ACTION_TAKEN'
}

export enum PrizeStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}
